variables:
  DEV_TAG: dev
stages:
  - build
  - deploy-prod
  - deploy-dev

build:
  image: node:16
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG != null'
  cache:
    key: "$CI_PROJECT_NAME--$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy-prod:
  image: docker:stable
  stage: deploy-prod
  before_script:
    - docker login $REGISTRY_URL
    - 'which ssh || ( apk add --update openssh )'
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_TAG != null && $DEV_TAG !~ $CI_COMMIT_TAG'
  script:
    - docker pull $REGISTRY_URL/$CONTAINER_IMAGE:latest || true
    - docker tag $REGISTRY_URL/$CONTAINER_IMAGE:latest $REGISTRY_URL/$CONTAINER_IMAGE:rollback || true
    - docker build -f Dockerfile.ci --cache-from $REGISTRY_URL/$CONTAINER_IMAGE:rollback --tag $REGISTRY_URL/$CONTAINER_IMAGE:latest --tag $REGISTRY_URL/$CONTAINER_IMAGE:$CI_COMMIT_TAG .
    - docker push $REGISTRY_URL/$CONTAINER_IMAGE:latest
    - docker push $REGISTRY_URL/$CONTAINER_IMAGE:rollback
    - docker push $REGISTRY_URL/$CONTAINER_IMAGE:$CI_COMMIT_TAG
    - ssh $SSH_USER -i $SSH_KEY_LOCATION "cd $COMPOSE_LOCATION && docker-compose up -d $COMPOSE_SERVICE"

deploy-dev:
  image: docker:stable
  stage: deploy-dev
  before_script:
    - docker login $REGISTRY_URL
    - 'which ssh || ( apk add --update openssh )'
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_TAG != null && $DEV_TAG =~ $CI_COMMIT_TAG'
  script:
    - docker pull $REGISTRY_URL/$CONTAINER_IMAGE:latest-dev || true
    - docker tag $REGISTRY_URL/$CONTAINER_IMAGE:latest-dev $REGISTRY_URL/$CONTAINER_IMAGE:rollback-dev || true
    - docker build -f Dockerfile.ci --cache-from $REGISTRY_URL/$CONTAINER_IMAGE:rollback-dev --tag $REGISTRY_URL/$CONTAINER_IMAGE:latest-dev --tag $REGISTRY_URL/$CONTAINER_IMAGE:$CI_COMMIT_TAG .
    - docker push $REGISTRY_URL/$CONTAINER_IMAGE:latest-dev
    - docker push $REGISTRY_URL/$CONTAINER_IMAGE:rollback-dev
    - docker push $REGISTRY_URL/$CONTAINER_IMAGE:$CI_COMMIT_TAG
