FROM nginx:latest

COPY dist /usr/share/nginx/html
COPY ./default.tmpl /etc/nginx/conf.d/default.tmpl

CMD /bin/bash -c "envsubst '\$VUE_APP_API_BASE_URL' < /etc/nginx/conf.d/default.tmpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
